!wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww!
!---------------------------------------------------------------------!
!                        INPUT PARALLEL FILE                          !
!                      Miguel Angel Uh Zapata                         !
!                             Jun 2014                                !
!---------------------------------------------------------------------!
!wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww!


      SUBROUTINE parallel_input_global

!---------------------------------------------------------------------!
!                                                                     !
!    This program reads the data files:                               !
!                  -   data.txt                                       !
!                  -   dataChaco.txt                                  !
!    corresponding to the data of the physical domain generated by    !
!    our mesh generator and by Chaco program and save it in global    !
!    data variables.                                                  ! 
!                                                                     !
!---------------------------------------------------------------------!
!                                                                     !
!    Output variables:                                                !
!   _______________________________________________________________   !
!  |       Name       |    Dimension    |       Description        |  !  
!  |__________________|_________________|__________________________|  !   
!  |                  |                 |                          |  !
!  | <--- No_vp_global|(N_CELL0global,3)| Neighbors vertices       |  !
!  | <--- No_cp_global|(N_CELL0global,3)| Neighbors cell-centers   |  !
!  | <--- nbe_global  |(N_CELL0global)  | Type of cell-center      |  !        
!  | <--- xv_global   |(N_VERTglobal)   | x-vertex coordinate      |  !
!  | <--- yv_global   |(N_VERTglobal)   | y-vertex coordinate      |  !
!  | <--- zbv_global  |(N_VERTglobal)   | Water levels             |  !
!  | <--- No_wb_global|(N_WBglobal)     | Boundary vert. WALL      |  !
!  | <--- No_qb_global|(N_QBglobal)     | Boundary vert. DISCHARGE |  !
!  | <--- No_hb_global|(N_HBglobal      | Boundary vert. WATER     |  !
!  | <--- No_sp_global|(N_SPglobal)     | Sample cell-center elem. |  !
!  |__________________|_________________|__________________________|  ! 
!  |                  |                 |                          |  !
!  | <--- TagParallel |(N_CELL0global)  | Subdomain tag (parallel) |  !
!  |__________________|_________________|__________________________|  ! 
!                                                                     !
!---------------------------------------------------------------------!

!*********************************************************************!
!                                                                     !
!                           Definitions                               !
!                                                                     !
!*********************************************************************!
!     ____________________________________
!    |                                    |
!    |     Keys and common parameters     |
!    |____________________________________|

#     include "cppdefs.h"
!     ====================================
!     ==========  SEQUENTIAL =============
#     ifndef KeyParallel
            USE geometry
            implicit none
#     endif
!     ====================================
!     =====  START PARALLEL OPTION =======
#     ifdef KeyParallel
            USE parallel
            USE geometry
            implicit none
#     endif
!     =============== END ================    
!     ====================================  
!     ____________________________________
!    |                                    |
!    |   Declaration of local variables   |
!    |____________________________________|

      integer :: ii,s,s0,i0,j0,k0,m,sm,tag
      integer :: Jini,Jfin,Iini,Ifin
      integer :: Ielem,Jelem,Jvertex,Ivertex,kelem
      integer :: jc,jc1,jc2,jc3
      integer :: jv,jv1,jv2,jv3
      integer :: elem,irec,NNbefore
      real*8  :: xxc,yyc
!     ------------------------------
      character*80 title
      character*36 filen
      character*39 filen2

!     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#     ifdef KeyDbg
           print*, '      ----> Begin subroutine: parallel_input'
#     endif
!     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

!*********************************************************************!
!                                                                     !
!                   Read data files:  data.txt                        !
!                                     dataChaco.txt                   !
!                                                                     !
!*********************************************************************!

      allocate(No_vp_global(N_CELL0global,3)) 
      allocate(No_cp_global(N_CELL0global,3)) 
      allocate(nbe_global(N_CELL0global))              
      allocate(xv_global(N_VERTglobal)) 
      allocate(yv_global(N_VERTglobal)) 
      allocate(zbv_global(N_VERTglobal))

74    format(A46)
85    format(20I7)
86    format(10F8.3)
87    format(2F15.5)
88    format(3I8)
89    format(I8)
!      ________________________________________________________
!     |                                                        |
!     |                Read data file: data.txt                |
!     |________________________________________________________|

!     ________________________________________________________
!     Open file

!     ________________________________
#     if defined(KeyEstuaryGironde)
         open(22,file='EstuaryGironde/data.txt',status='OLD')
!     ________________________________
#     elif defined(KeyStaticCylinder)
         open(22,file='StaticCylinder/data.txt',status='OLD')
!     ________________________________
#     elif defined(KeyStaticChannel)
         open(22,file='StaticChannel/data.txt',status='OLD')
!     ________________________________
#     elif defined(KeyStandingWave)
         open(22,file='StandingWave/data.txt',status='OLD')
!     ________________________________
#     elif defined(KeyTaylorVortex)
         open(22,file='TaylorVortex/data.txt',status='OLD')
!     ________________________________
#     elif defined(KeyTestOnlyPoisson)
         open(22,file='TestOnlyPoisson/data.txt',status='OLD')
!     ________________________________
#     else
         open(22,file='data.txt',status='OLD')
#     endif

!     ________________________________________________________
!     Read: Number of cell-center and vertex points  
      read(22,74) title
      read(22,74) title
      read(22,74) title
!     ________________________________________________________
!     Read: Numbering of the cell vertices for each element 

      read(22,74) title
      read(22,88) ((No_vp_global(i,j),j=1,3),i=1,N_CELL0global)
!     ________________________________________________________
!     Read: Coordinates of cell vertices 
      read(22,74) title
      read(22,87) (xv_global(nv),yv_global(nv),nv=1,N_VERTglobal) 
!     changed the domain size to be half
!     ________________________________________________________
!     Read: Numbering of the surrounding three cell centers

      read(22,74) title
      read(22,88) ((No_cp_global(i,j),j=1,3),i=1,N_CELL0global)
!     ________________________________________________________
!     Read: Bottom levels

      read(22,74) title
      read(22,86) (zbv_global(nv),nv=1,N_VERTglobal)
!     ________________________________________________________
!     Read: Type of cell (inside or boundary)    

      read(22,74) title
      read(22,85) (nbe_global(i),i=1,N_CELL0global) 
!     ________________________________________________________
!     Read: Inputting for wall boundary vertices           

      read(22,74) title
      read(22,*)  N_WBglobal
      allocate(No_wb_global(N_WBglobal))
      if (N_WBglobal.ne.0) then
	 read(22,85) (No_wb_global(nv),nv=1,N_WBglobal)
      else
         read(22,74) title
      endif
!     ________________________________________________________
!     Read: Inputting for discharge normal to boundary vert
					 
      read(22,74) title
      read(22,*)  N_QBglobal	
      allocate(No_qb_global(N_QBglobal))
      if (N_QBglobal.ne.0) then
	 read(22,85) (No_qb_global(nv),nv=1,N_QBglobal) 
      else
         read(22,74) title
      endif
!     ________________________________________________________
!     Read: Inputting for water level boundary vertices   
					
      read(22,74) title
      read(22,*)  N_HBglobal
      allocate(No_hb_global(N_HBglobal))	
      if (N_HBglobal.ne.0) then
	 read(22,85) (No_hb_global(nv),nv=1,N_HBglobal)
      else
         read(22,74) title
      endif 
!     ________________________________________________________
!     Read: Number of sampling vertices    
                   
      read(22,74) title
      read(22,*)  N_SPglobal
      allocate(No_sp_global(N_SPglobal))
      if (N_SPglobal.ge.1) then
	 read(22,85) (No_sp_global(nv),nv=1,N_SPglobal)
      endif
!     ________________________________________________________
!     Close file
      close(22)

!      ________________________________________________________
!     |                                                        |
!     |                   Read the data file                   |
!     |________________________________________________________|

      allocate(TagParallel(N_CELL0global))

!     ________________________________________________________
!     Open file

!     ________________________________
#     if defined(KeyEstuaryGironde)
         open(22,file='EstuaryGironde/dataChaco.txt',status='OLD')
!     ________________________________
#     elif defined(KeyStaticCylinder)
         if (Nprocs.eq.2) then 
            open(12,file='StaticCylinder/dataChaco02.txt',status='old')
         elseif (Nprocs.eq.4) then 
            open(12,file='StaticCylinder/dataChaco04.txt',status='old')
         elseif (Nprocs.eq.8) then 
            open(12,file='StaticCylinder/dataChaco08.txt',status='old')
         elseif (Nprocs.eq.16)then 
            open(12,file='StaticCylinder/dataChaco16.txt',status='old')
         elseif (Nprocs.eq.32)then 
            open(12,file='StaticCylinder/dataChaco32.txt',status='old')
         else 
            open(12,file='StaticCylinder/dataChaco.txt',status='old')
         endif
!     ________________________________
#     elif defined(KeyStaticChannel)
         if (Nprocs.eq.2) then 
            open(12,file='StaticChannel/dataChaco02.txt',status='old')
         elseif (Nprocs.eq.4) then 
            open(12,file='StaticChannel/dataChaco04.txt',status='old')
         elseif (Nprocs.eq.8) then 
            open(12,file='StaticChannel/dataChaco08.txt',status='old')
         elseif (Nprocs.eq.16)then 
            open(12,file='StaticChannel/dataChaco16.txt',status='old')
         elseif (Nprocs.eq.32)then 
            open(12,file='StaticChannel/dataChaco32.txt',status='old')
         else 
            open(12,file='StaticChannel/dataChaco.txt',status='old')
         endif
!     ________________________________
#     elif defined(KeyStandingWave)
         if (Nprocs.eq.2) then 
            open(12,file='StandingWave/dataChaco02.txt',status='old')
         elseif (Nprocs.eq.4) then 
            open(12,file='StandingWave/dataChaco04.txt',status='old')
         elseif (Nprocs.eq.8) then 
            open(12,file='StandingWave/dataChaco08.txt',status='old')
         elseif (Nprocs.eq.16)then 
            open(12,file='StandingWave/dataChaco16.txt',status='old')
         elseif (Nprocs.eq.32)then 
            open(12,file='StandingWave/dataChaco32.txt',status='old')
         else 
            open(12,file='StandingWave/dataChaco.txt',status='old')
         endif
!     ________________________________
#     elif defined(KeyTaylorVortex)
         if (Nprocs.eq.2) then 
            open(12,file='TaylorVortex/dataChaco02.txt',status='old')
         elseif (Nprocs.eq.4) then 
            open(12,file='TaylorVortex/dataChaco04.txt',status='old')
         elseif (Nprocs.eq.8) then 
            open(12,file='TaylorVortex/dataChaco08.txt',status='old')
         elseif (Nprocs.eq.16)then 
            open(12,file='TaylorVortex/dataChaco16.txt',status='old')
         elseif (Nprocs.eq.32)then 
            open(12,file='TaylorVortex/dataChaco32.txt',status='old')
         else 
            open(12,file='TaylorVortex/dataChaco.txt',status='old')
         endif
!     ________________________________
#     elif defined(KeyTestOnlyPoisson)
         if (Nprocs.eq.2) then 
            open(12,file='TestOnlyPoisson/dataChaco02.txt',status='old')
         elseif (Nprocs.eq.4) then 
            open(12,file='TestOnlyPoisson/dataChaco04.txt',status='old')
         elseif (Nprocs.eq.8) then 
            open(12,file='TestOnlyPoisson/dataChaco08.txt',status='old')
         elseif (Nprocs.eq.16)then 
            open(12,file='TestOnlyPoisson/dataChaco16.txt',status='old')
         elseif (Nprocs.eq.32)then 
            open(12,file='TestOnlyPoisson/dataChaco32.txt',status='old')
         else 
            open(12,file='TestOnlyPoisson/dataChaco.txt',status='old')
         endif
!     ________________________________
#     else
         open(22,file='dataChaco.txt',status='OLD')
#     endif

!     ________________________________________________________
!     Read: Tags corresponding for each subdomain 

      do i=1,N_CELL0global
         read(12,89) TagParallel(i)
      enddo
!     ________________________________________________________
!     Close file

      close(12)


!*********************************************************************!
!                                                                     !
!                             Finalization                            !
!                                                                     !
!*********************************************************************!

      IF (rang_topo.eq.0) THEN  
      print*,'_________________________________________________________'
      print*,'                                                         ' 
      print*,'    ==================================================  '
      print*,'                   MPI: Reading data                     '
      print*,'    ==================================================  '
      print*,'                                                         ' 
      print*,'      -- data.txt      has been succefully read --       '
      print*,'      -- dataChaco.txt has been succefully read --       '
      print*,'                                                         '
      ENDIF
#     ifdef KeyDisplayParallel
      IF (rang_topo.eq.0) THEN  
      print*,'                                                         '
      print*,'  Num. of vertices      :  N_VERTglobal  =',N_VERTglobal
      print*,'  Num. of cell-centers  :  N_CELL0global =',N_CELL0global
      print*,'  Num. of wall  vertices:  N_WBglobal    =',N_WBglobal
      print*,'  Num. of disch vertices:  N_QBglobal    =',N_QBglobal
      print*,'  Num. of water vertices:  N_HBglobal    =',N_HBglobal      
      print*,'                                                         '
      ENDIF
#     endif

!     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#     ifdef KeyDbg
           print*, '      ----> End   subroutine: parallel_input'
#     endif
!     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

      RETURN
      END


!wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww!
!---------------------------------------------------------------------!
!                      	   END OF INPUT                               !
!---------------------------------------------------------------------!
!wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww!

